### ISSUE TITLE
CSS 并不简单 -- 文字修饰的那点事

### ISSUE THREAD

**Issue by 15751165579** [15751165579/ThinkInCoding#13]
> 这篇主要介绍一些文字修饰的相关技巧。这里主要从text-decoration和text-shadow这两个属性聊起

### 一、text-decoration

&emsp;&emsp;相信大家对于text-decoration这个属性并不陌生，在重置a标签的默认样式时，我们经常要这样写：text-decoration: none;可能对它了解的人也很少，实际上text-decoration是一个复合属性，由line、style和color组成。

&emsp;&emsp;所以我们可以实现这样的效果：
![下划黄色虚线](https://user-gold-cdn.xitu.io/2017/6/3/8494b2df15ba6e75ca6cf5ffe8d987fc)

&emsp;&emsp;可惜的是line只有underline(下划线)、overline(上划线)和line-through(删除线)。如果突然需要下划波浪线，怎么办呢？不要急，神奇的CSS会帮你做到的。首先，你需要先了解一下[渐变的使用技巧](http://www.jianshu.com/p/3b9c19746d6c)。先上效果图吧:

![渐变实现文字波浪线](https://user-gold-cdn.xitu.io/2017/6/3/02888c1ad40b9e4374288428810756bc)

&emsp;&emsp;说一下这里的思路，我们首先要用两段渐变构造一个基本元素：'X'(这里我就不放图了)，下一步就比较重要了，我们要截取'X'的上半部分，得到一个'V',从而结合repeat形成波浪线。下面是用scss写的一个mixin，方便以后使用。

```css
    @mixin waveline($color,$h) {
        position: relative;
        &::after {
            content: '';
            display: block;
            position: absolute;
            top: 100%;
            left: 0;
            width: 100%;
            height: $h;
            background: linear-gradient(135deg, transparent, transparent 45%, $color, transparent 55%, transparent 100%),
                        linear-gradient(45deg, transparent, transparent 45%, $color, transparent 55%, transparent 100%);
            background-size: $h * 2 $h * 2;
        }
    }
```

### 二、text-shadow

&emsp;&emsp;对于text-shadow和box-shadow几乎差不多，它也支持逗号语法，所以它可以生成多个阴影，这里我们要介绍几个简单的应用：

#### 1、文字的3D效果

&emsp;&emsp;这种3D也是利用多重阴影的技巧，下面效果图：

![text-shadow实现3D效果](https://user-gold-cdn.xitu.io/2017/6/3/ce64410b5357f01daf7b169e24a94a6c)

```css
    @mixin threeDText($color) {
        text-shadow: 1px 1px $color, 2px 2px $color,
                     3px 3px $color, 4px 4px $color,
                     5px 5px $color, 6px 6px $color,
                     7px 7px $color, 8px 8px $color;
    }
```

&emsp;&emsp;这里几个颜色需要调节得当，效果才会好一点。

#### 2、文字描边效果

&emsp;&emsp;下面效果图：

![text-shadow实现文字描边效果](https://user-gold-cdn.xitu.io/2017/6/3/340f58d66375fdf7b2b5fe980997ba11)

```css
    @mixin strokeText($w, $color) {
        text-shadow: $w 0 0 $color,
                     -$w 0 0 $color,
                     0 $w 0 $color,
                     0 -$w 0 $color;
    }
```

&emsp;&emsp;其实这里的效果并不是特别的好，但是可以让我们惊叹小小的属性，大大的用法。

### 写在结尾

&emsp;&emsp;可能这次写的有点东西有点少，并没有让你看的过瘾，不要急，下期更精彩。^_^
