### ISSUE TITLE
CSS并不简单--结合SVG实现简单的加载动画

### ISSUE THREAD

**Issue by 15751165579** [15751165579/ThinkInCoding#19]
> 今天通过两个简单的加载动画让大家见识一下CSS与SVG结合的威力。

### 一、你需要准备什么？

&emsp;&emsp;对于svg，可能一些刚接触前端的同学比较的陌生。你可以先去MDN上看一下基本的介绍。本篇内容最重要的一个知识点就是stroke-dasharray和stroke-offset的组合使用。

&emsp;&emsp;这里你可以先看一下[张鑫旭对于stroke相关属性的介绍](http://www.zhangxinxu.com/wordpress/2014/04/animateion-line-drawing-svg-path-%E5%8A%A8%E7%94%BB-%E8%B7%AF%E5%BE%84/)

### 二、加载等待动画

&emsp;&emsp;这个动画大家应该很熟悉：
![支付宝的一种加载动画](https://user-gold-cdn.xitu.io/2017/7/11/4fc83131c0371124725c8ec0018e91cb)

&emsp;&emsp;这个难度不是很大，本质上就是一个小圆弧在圆环上旋转。

```html
    svg(viewBox="0 0 50 50")
        circle(class="item" cx="25" cy="25" r="20" fill="none")
        circle(class="item" cx="25" cy="25" r="20" fill="none")
```

&emsp;&emsp;对于圆环的设置我们采用stroke-dasharray来实现:

```css
    .item:nth-child(2) {
        stroke: rgb(24,120,222);
        stroke-width: 2px;
        stroke-dasharray: 10, 300;
        stroke-linecap: round;
   }
```

&emsp;&emsp;接下来重点来了，我们需要通过transform让图形旋转。一谈到 transform不得不要注意transform-origin的设置。对于HTML中的元素，我们通过transform-origin的设置，很容易就解决了。但是SVG中的transform变化就没这么简单，这里有一篇很好文章作为参考[张鑫旭SVG transform坐标变换](http://www.zhangxinxu.com/wordpress/2015/10/understand-svg-transform/)

&emsp;&emsp;这里我就采用比较朴实的方法，旋转SVG：

```css
    svg {
        animation: zfbloading 1.4s linear infinite;
    }
    
    @keyframes zfbloading {
        0% {
            transform: rotate(0deg);
        }
        100% {
            transform: rotate(360deg);
        }
    }
```

### 三、加载失败动画

&emsp;&emsp;接下来我们实现这样的效果：

![加载失败动画](https://user-gold-cdn.xitu.io/2017/7/11/bef525521063a88c165a7e79e703aaf0)

&esmp;&emsp;首先看一下它的结构：

```html
    svg(viewBox="0 0 100 100")
        circle(cx="50" cy="50" r="40" fill="none")
        path(class="line1" d="M30 30 L70 70" fill="none")
        path(class="line2" d="M70 30 L30 70" fill="none")
```

&emsp;&emsp;首先对于外圈的动画我们还是采用stroke-dasharray和stroke-dashoffset来实现。但是这里你要完完全全的理解这两个属性的用法（好好看看上文提供的张鑫旭的文章），他通过一个火腿肠的例子很好的讲解了这两者的用法。

&emsp;&emsp;从动画效果可以看出，小圆弧在旋转的过程中长度由短边长，由长变短，最后形成一个圆。

```css
    @keyframes loading {
        0% {
            stroke-dasharray: 0, 251;
            stroke-dashoffset: 0;
        }
        35% {
            stroke-dasharray: 86, 86;
            stroke-dashoffset: -86;
        }
        70% {
            stroke-dasharray: 0, 251;
            stroke-dashoffset: -251;
        }
        100% {
            stroke-dasharray: 251, 0;
            stroke-dashoffset: -251;
        }
    }
```

&emsp;&emsp;对于上述CSS代码中的251，你可以通过JS中的getTotalLength方法获取到。

&emsp;&emsp;对于叉号的动画效果，我们仍然采用的是stroke-dasharray和stroke-dashoffset实现。到这里你应该明白了这两个属性的重要性。再通过animation-delay设置动画的衔接。

### 四、总结

&emsp;&emsp;显然SVG的魅力不止于此，下次再见。
