### ISSUE TITLE
CSS并不简单--生冷而又发光的属性

### ISSUE THREAD

**Issue by 15751165579** [15751165579/ThinkInCoding#26]
> 这里主要记录一些不常见但是有很有效果的CSS属性。

### 一、-webkit-touch-callout

&emsp;&emsp;这是一个非标准属性，当你在iOS上长按目标元素，Safari会展示一个关于这个链接的callout信息，如果我们要取消这样的回馈：

```css
    a, img {
        -webkit-touch-callout: none;
    }
```

### 二、-webkit-tap-highlight-color

&emsp;&emsp;非标准属性。在移动端，你点击链接会给你一个高亮颜色，十分的讨厌，用这个属性就可以解决了：

```css
    *, ::before, ::after {
        box-sizing: border-box;
        -webkit-tap-highlight-color: transparent;
    }
```

### 三、text-size-adjust

&emsp;&emsp;非标准属性。当值为none时，禁止调整字体大小。

### 四、touch-action

&emsp;&emsp;设置元素上支持的一些手势。

### 五、font-smoothing

&emsp;&emsp;非标准属性。从名称就可以知道它的作用，一般这样设置：

```css
    -webkit-font-smoothing: antialiased;
```

### 六、user-select

&emsp;&emsp;通常设置它不能让用户选择文字：

```css
    user-select: none;
```
